applications:
  django-app:
    enabled: true
    name: django-app
    namespace: argocd
    project: default
    repoURL: https://github.com/Emiliia8888/final-project.git
    targetRevision: main
    path: charts/django-app

repositories:
  django-app:
    type: git
    url: https://github.com/Emiliia8888/final-project.git
