alertmanager:
  enabled: true

grafana:
  enabled: true
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus:
  enabled: true
