controller:
  serviceType: LoadBalancer

  admin:
    createSecret: true

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code

persistence:
  enabled: true
  size: 10Gi

serviceAccount:
  create: true

rbac:
  create: true

controller:
  serviceType: LoadBalancer
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
