apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.helm.sh/release-name: django-app
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2026-08-08T23:00:25Z"
  generation: 5336
  labels:
    app.kubernetes.io/managed-by: Helm
  name: django-app
  namespace: argocd
  resourceVersion: "13875779"
  uid: 8d52d9ae-3eed-4a45-a1bc-0e693f86b442
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/django-app
    repoURL: https://github.com/Emiliia8888/Lesson-8-9.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2026-08-14T19:26:32Z"
    deployedAt: "2026-08-14T19:26:33Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 4f00088118d69f4bf7a0ea285a0855709dd0eaa8
    source:
      path: charts/django-app
      repoURL: https://github.com/Emiliia8888/Lesson-8-9.git
      targetRevision: main
  - deployStartedAt: "2026-08-16T12:14:54Z"
    deployedAt: "2026-08-16T12:14:54Z"
    id: 1
    initiatedBy:
      automated: true
    revision: 58da3e8c779f955516477be53bf6f13b83d4435d
    source:
      path: charts/django-app
      repoURL: https://github.com/Emiliia8888/Lesson-8-9.git
      targetRevision: main
  - deployStartedAt: "2026-08-17T14:05:48Z"
    deployedAt: "2026-08-17T14:05:49Z"
    id: 2
    initiatedBy:
      automated: true
    revision: ab1ce58dec922d4dac9bfc5d2f3443e4b42cb553
    source:
      path: charts/django-app
      repoURL: https://github.com/Emiliia8888/Lesson-8-9.git
      targetRevision: main
  - deployStartedAt: "2026-08-17T15:05:48Z"
    deployedAt: "2026-08-17T15:05:49Z"
    id: 3
    initiatedBy:
      automated: true
    revision: 2f36bf7454acfe3c990386230831b7bf8edd5953
    source:
      path: charts/django-app
      repoURL: https://github.com/Emiliia8888/Lesson-8-9.git
      targetRevision: main
  - deployStartedAt: "2026-08-17T15:23:48Z"
    deployedAt: "2026-08-17T15:23:49Z"
    id: 4
    initiatedBy:
      automated: true
    revision: 85170e9d74c8b9d34abe1c6f6b1667fe4b2b621e
    source:
      path: charts/django-app
      repoURL: https://github.com/Emiliia8888/Lesson-8-9.git
      targetRevision: main
  operationState:
    finishedAt: "2026-08-17T15:23:49Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        autoHealAttemptsCount: 4
        prune: true
        revision: 85170e9d74c8b9d34abe1c6f6b1667fe4b2b621e
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2026-08-17T15:23:48Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/django-app-django-app-config unchanged
        name: django-app-django-app-config
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/django-app-service unchanged
        name: django-app-service
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/django-app-django-app configured
        name: django-app-django-app
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: horizontalpodautoscaler.autoscaling/django-app-hpa unchanged
        name: django-app-hpa
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v2
      revision: 85170e9d74c8b9d34abe1c6f6b1667fe4b2b621e
      source:
        path: charts/django-app
        repoURL: https://github.com/Emiliia8888/Lesson-8-9.git
        targetRevision: main
  reconciledAt: "2026-08-19T12:16:26Z"
  resources:
  - kind: ConfigMap
    name: django-app-django-app-config
    namespace: default
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: django-app-service
    namespace: default
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: django-app-django-app
    namespace: default
    status: Synced
    version: v1
  - group: autoscaling
    health:
      message: the HPA controller was able to get the target's current scale
      status: Healthy
    kind: HorizontalPodAutoscaler
    name: django-app-hpa
    namespace: default
    status: Synced
    version: v2
  - group: batch
    hook: true
    kind: Job
    name: django-app-migrate
    namespace: default
    requiresPruning: true
    version: v1
  sourceType: Helm
  summary:
    images:
    - 034255117140.dkr.ecr.eu-central-1.amazonaws.com/django-app-gitops:34
    - 034255117140.dkr.ecr.eu-central-1.amazonaws.com/django-app:38ea3cc-amd64
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        path: charts/django-app
        repoURL: https://github.com/Emiliia8888/Lesson-8-9.git
        targetRevision: main
    revision: b72346b7fe814009f10abf28b130b3f2b4b3dce9
    status: Synced
