apiVersion: v1
data:
  DB_PASSWORD: REDACTED
  SECRET_KEY: REDACTED
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: django-app:/Secret:default/django-app-django-app-secret
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB_PASSWORD":"REDACTED","SECRET_KEY":"REDACTED"},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"django-app:/Secret:default/django-app-django-app-secret"},"name":"django-app-django-app-secret","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2026-07-16T17:07:08Z"
  name: django-app-django-app-secret
  namespace: default
  resourceVersion: "2576020"
  uid: 332ec8ee-8847-4a82-b240-c222c60942bd
type: Opaque
