image:
  repository: "123456789012.dkr.ecr.us-east-1.amazonaws.com/django-app"
  tag: "latest"
  pullPolicy: Always

replicaCount: 1

containerPort: 8000


database:
  host: "django-rds-instance.ctskymysi6zv.eu-central-1.rds.amazonaws.com"
  name: "django"
  username: "django_admin"
