apiVersion: v1
data:
  ALLOWED_HOSTS: '*'
  DB_HOST: django-rds-migration-final.ctskymysi6zv.eu-central-1.rds.amazonaws.com
  DB_NAME: django
  DB_PORT: "5432"
  DB_USER: django_admin
  DJANGO_DEBUG: "False"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ALLOWED_HOSTS":"*","DB_HOST":"django-rds-migration-final.ctskymysi6zv.eu-central-1.rds.amazonaws.com","DB_NAME":"django","DB_PORT":"5432","DB_USER":"django_admin","DJANGO_DEBUG":"False"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"django-app"},"name":"django-app-django-app-config","namespace":"default"}}
  creationTimestamp: "2026-08-14T19:26:33Z"
  labels:
    argocd.argoproj.io/instance: django-app
  name: django-app-django-app-config
  namespace: default
  resourceVersion: "13168473"
  uid: 4572e05e-bc8b-4aa0-a357-041ad7b71e00
