replicaCount: 2

image:
  repository: "034255117140.dkr.ecr.eu-central-1.amazonaws.com/django-app"
  tag: "38ea3cc-amd64"
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

django:
  debug: "False"
  allowedHosts: "*"
  # SECRET_KEY is supplied by Kubernetes Secret

db:
  name: "django"
  user: "django_admin"
  host: "django-rds-migration-final.ctskymysi6zv.eu-central-1.rds.amazonaws.com"
  port: "5432"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
