apiVersion: batch/v1
kind: Job

metadata:
  name: django-app-migrate
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: migrate

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        command:
        - python
        - manage.py
        - migrate

env:
  - name: DJANGO_SETTINGS_MODULE
    value: "core.settings"

  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: django-config
        key: DB_HOST

  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: django-config
        key: DB_NAME

  - name: DB_USER
    valueFrom:
      configMapKeyRef:
        name: django-config
        key: DB_USER

  - name: DB_PORT
    valueFrom:
      configMapKeyRef:
        name: django-config
        key: DB_PORT

  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: django-secret
        key: DB_PASSWORD
